DPRS-656: Updates to reg w/o id
hmrc/dprs pull request #15
Opened 2024-06-10 15:25 UTC by paddynski-opencast

2024-06-11 12:46 UTC, erasmos-hmrc-new requested changes

2024-06-11 12:46 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/RegistrationConverterBaseSpec.scala
> +abstract class RegistrationConverterBaseSpec extends BaseSpec {
We don't need this.

2024-06-11 12:46 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForIndividualConverterSpec.scala
> +        common = expectedCommon(),
Inline object.

2024-06-11 12:46 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForOrganisationConverterSpec.scala
> +        common = expectedCommon(),
Inline object.

2024-06-11 12:46 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withId/RegistrationConverterWithIdForOrganisationConverterSpec.scala
> +          common = expectedCommon(),
Inline.

2024-06-11 12:46 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForIndividualConverterSpec.scala
> +        common = expectedCommon(),
Inline.

2024-06-11 12:46 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withId/RegistrationConverterWithIdForIndividualConverterSpec.scala
> +        common = expectedCommon(),
Inline.

2024-06-11 12:46 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/converters/registration/RegistrationConverter.scala
> +  val regime = "DPRS"
This only used in this class, so can go into the class, and made private.

```
final private val regime = "DPRS".
```

2024-06-11 13:17 UTC, paddynski-opencast commented on app/uk/gov/hmrc/dprs/converters/registration/RegistrationConverter.scala
> +  val regime = "DPRS"
Done.

2024-06-11 13:18 UTC, paddynski-opencast commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForIndividualConverterSpec.scala
> +        common = expectedCommon(),
Done.

2024-06-11 13:18 UTC, paddynski-opencast commented on test/uk/gov/hmrc/dprs/converters/registration/withId/RegistrationConverterWithIdForOrganisationConverterSpec.scala
> +          common = expectedCommon(),
Done.

2024-06-11 13:18 UTC, paddynski-opencast commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForIndividualConverterSpec.scala
> +        common = expectedCommon(),
Done.

2024-06-11 13:19 UTC, paddynski-opencast commented on test/uk/gov/hmrc/dprs/converters/registration/RegistrationConverterBaseSpec.scala
> +abstract class RegistrationConverterBaseSpec extends BaseSpec {
Removed.

2024-06-11 14:03 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/RegistrationConverterBaseSpec.scala
> +abstract class RegistrationConverterBaseSpec extends BaseSpec {
Confirmed.

2024-06-11 14:04 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForIndividualConverterSpec.scala
> +        common = expectedCommon(),
Confirmed.

2024-06-11 14:04 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withId/RegistrationConverterWithIdForOrganisationConverterSpec.scala
> +          common = expectedCommon(),
Confirmed.

2024-06-11 14:05 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/converters/registration/RegistrationConverter.scala
> +  val regime = "DPRS"
Confirmed.

2024-06-11 14:06 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForOrganisationConverterSpec.scala
> +        common = expectedCommon(),
Confirmed.

2024-06-11 14:06 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/converters/registration/withoutId/RegistrationConverterWithoutIdForIndividualConverterSpec.scala
> +        common = expectedCommon(),
Confirmed.

2024-06-12 08:10 UTC, erasmos-hmrc-new commented
```
ACCESS_LOG_FILE appender (and usage) can be removed from ...
```

I think this isn't correct, as we can see a reference in the same file:

```
    <logger name="accesslog" level="INFO" additivity="false">
        <appender-ref ref="ACCESS_LOG_FILE" />
    </logger>
```

So let's leave it in.

2024-06-12 08:23 UTC, erasmos-hmrc-new commented on etc/postman/RegistrationWithoutID.json
> +							"name": "Forbidden",
Both of these 'forbidden' scenarios should be in the Failure / Downstream folders:

<img width="281" alt="image" src="https://github.com/hmrc/dprs/assets/144703494/f859677a-db3a-4bfc-a478-9ce32fdf2d20">

2024-06-12 09:01 UTC, paddynski-opencast commented on etc/postman/RegistrationWithoutID.json
> +							"name": "Forbidden",
Moved both scenarios.

2024-06-12 09:23 UTC, erasmos-hmrc-new approved these changes

2024-06-12 09:30 UTC, merged