DPRS-1080: Update Stubs & Backend Support For Subscription Read (v1.6)
hmrc/dprs pull request #17
Opened 2024-06-21 09:51 UTC by paddynski-opencast

2024-06-24 15:57 UTC, erasmos-hmrc-new requested changes

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on etc/postman/ReadSubscription.json
> +		"_exporter_id": "25291378"
In Success / Success, it would be good to have a small verification of the body:

```
pm.test("Has the expected id", function () {
    pm.expect(pm.response.json().id).to.eql("XLD1234567891");
});
```

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on etc/postman/ReadSubscription.json
> +											"pm.test(\"Response body is enpty\", function () {",
Typo: `enpty` -> `empty`.

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-09-07T14:02:47.029Z",
Use `$currentDateAndTime`.

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-09-07T14:02:47.029Z",
Use `$currentDateAndTime`.

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-08-31T13:00:21.655Z",
Use `$currentDateAndTime`.

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +            INTERNAL_SERVER_ERROR,
Let's keep this as `SERVICE_UNAVAILABLE`.

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/services/subscription/ReadSubscriptionService.scala
> +        val badGateway              = "502"
Unused.

2024-06-24 15:57 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +            BAD_GATEWAY,
Let's use `SERVICE_UNAVAILABLE`.

2024-06-25 09:34 UTC, paddynski-opencast commented on etc/postman/ReadSubscription.json
> +		"_exporter_id": "25291378"
Added.

2024-06-25 09:37 UTC, paddynski-opencast commented on etc/postman/ReadSubscription.json
> +											"pm.test(\"Response body is enpty\", function () {",
Corrected.

2024-06-25 09:40 UTC, paddynski-opencast commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-09-07T14:02:47.029Z",
Changed.

2024-06-25 09:42 UTC, paddynski-opencast commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-09-07T14:02:47.029Z",
Changed/

2024-06-25 09:43 UTC, paddynski-opencast commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-08-31T13:00:21.655Z",
Changed.

2024-06-25 09:52 UTC, paddynski-opencast commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +            INTERNAL_SERVER_ERROR,
Changed.

2024-06-25 09:56 UTC, paddynski-opencast commented on app/uk/gov/hmrc/dprs/services/subscription/ReadSubscriptionService.scala
> +        val badGateway              = "502"
Removed.

2024-06-25 09:57 UTC, paddynski-opencast commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +            BAD_GATEWAY,
Changed.

2024-06-25 13:05 UTC, erasmos-hmrc-new commented on etc/postman/ReadSubscription.json
> +		"_exporter_id": "25291378"
Confirmed.

2024-06-25 13:06 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-09-07T14:02:47.029Z",
Confirmed.

2024-06-25 13:06 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +                               |        "timestamp": "2023-09-07T14:02:47.029Z",
Confirmed.

2024-06-25 13:07 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +            INTERNAL_SERVER_ERROR,
Confirmed.

2024-06-25 13:07 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/services/subscription/ReadSubscriptionService.scala
> +        val badGateway              = "502"
Confirmed.

2024-06-25 13:08 UTC, erasmos-hmrc-new commented on it/test/uk/gov/hmrc/dprs/subscription/ReadSubscriptionSpec.scala
> +            BAD_GATEWAY,
Confirmed.

2024-06-25 13:08 UTC, erasmos-hmrc-new commented on etc/postman/ReadSubscription.json
> +											"pm.test(\"Response body is enpty\", function () {",
Confirmed.

2024-06-25 13:13 UTC, merged