[ODPR-349] Added Backend Support For Subscription Read
hmrc/dprs pull request #8
Opened 2024-04-08 12:19 UTC by pauloncast

2024-04-08 14:17 UTC, erasmos-hmrc-new requested changes

2024-04-08 14:17 UTC, erasmos-hmrc-new commented on etc/postman/Read Subscription.json
> +{
Could you remove the space from the name?

2024-04-08 14:17 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/services/subscription/read/ReadSubscriptionServiceConverterSpec.scala
> +        }
And what if one or more contacts have neither individual nor organisation details?

2024-04-08 14:17 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/services/subscription/read/ReadSubscriptionServiceConverterSpec.scala
> +        }
And what if neither primary nor secondary contact is present?

2024-04-08 14:17 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/services/ReadSubscriptionService.scala
> +        case None =>
We shouldn't assume that they have organisation details, either. 

As well, use of 'get' is discouraged in Scala; much better to use pattern matching or map.

2024-04-09 10:02 UTC, pauloncast commented on etc/postman/Read Subscription.json
> +{
This has been fixed

2024-04-09 10:03 UTC, pauloncast commented on etc/postman/Read Subscription.json
> +	},
The folders and naming pattern has been updated for consistency

2024-04-09 10:09 UTC, pauloncast commented on test/uk/gov/hmrc/dprs/services/subscription/read/ReadSubscriptionServiceConverterSpec.scala
> +        }
Provision has been made to cater for these scenarios.
In a case without primary or secondary contact, a successful response with null `contacts` value is returned.
In a case with either of the contacts without individual or organisation details, a successful response is returned with only values for contact which are `landline` `mobile` and `emailAddress`

2024-04-09 10:12 UTC, pauloncast commented on app/uk/gov/hmrc/dprs/services/ReadSubscriptionService.scala
> +        case None =>
This has been refactored to use pattern matching on a tuple of individual and organisation details and a case for the absence of both has been handled to return contact with only the following values - `landline` `mobile` and `emailAddress`

2024-04-09 15:00 UTC, erasmos-hmrc-new commented on etc/postman/Read Subscription.json
> +	},
Confirmed.

2024-04-09 15:06 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/services/subscription/read/ReadSubscriptionServiceConverterSpec.scala
> +        }
Rather than null (Option) for contacts, let's just return an empty sequence.

And for the scenario "only primary contact without organisationDetails or individualDetails exists", if a contact lacks either detail, then ignore it entirely; you can revert Individual to have the mandatory fields.

2024-04-09 15:09 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/services/ReadSubscriptionService.scala
> +        case None =>
Yes, that's a better way to pattern match; however, best to return an optional Contact, and return `None` if both neither details are present, for it's not a contact of either kind.

And I'd add the case for both detail being present, also returning `None`.

For the latter two cases, we'll probably add logging at some point, but for now its enough to ignore the contact.

2024-04-10 08:16 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/services/subscription/read/ReadSubscriptionServiceConverterSpec.scala
> +        }
I can see that you're now excluding the incomplete contact, which is good.

However, I'd like for you to change the following in `ReadSubscriptionService.Responses`:

```
    final case class Response(id: String, name: Option[String], contacts: Option[Seq[Contact]])
```

to:

```
    final case class Response(id: String, name: Option[String], contacts: Seq[Contact])
```

An option of a sequence doesn't add any info (at least in this context), as the sequence can be empty.

2024-04-10 08:17 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/services/ReadSubscriptionService.scala
> +        case None =>
Good. Just replace the two unused vals on line 170, with underscores.

2024-04-10 09:16 UTC, erasmos-hmrc-new commented on app/uk/gov/hmrc/dprs/services/ReadSubscriptionService.scala
> +        case None =>
Confirmed.

2024-04-10 09:17 UTC, erasmos-hmrc-new commented on test/uk/gov/hmrc/dprs/services/subscription/read/ReadSubscriptionServiceConverterSpec.scala
> +        }
Confirmed.

2024-04-10 09:19 UTC, erasmos-hmrc-new approved these changes

2024-04-10 09:20 UTC, merged